# --- system parameters --- #
RELPATH = '.'
BASIC = 0
CBASIC = 0

# --- instance parameters --- #
PLACE = 'Cook County'
FILENAME = PLACE.replace(' ', '-')

# --- plotting parameters --- #
CENTER = (41.8781, -87.6298)
LINESCALING = 4
HEXBLACK = "#000000"
HEXORANGE = "#E69F00"
HEXSKYBLUE = "#56B4E9"
HEXBLUISHGREEN = "#009E73"
HEXYELLOW = "#F0E442"
HEXBLUE = "#0072B2"
HEXVERMILLION = "#D55E00"
HEXREDDISHPURPUPLE = "#CC79A7"
HEXCOLORS = [
    HEXYELLOW,
    HEXBLUE,
    HEXVERMILLION,
    HEXSKYBLUE,
    HEXORANGE,
    HEXBLUISHGREEN,
    HEXREDDISHPURPUPLE,
]
